# Generated by Django 4.1.4 on 2022-12-13 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('profile_image', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('current_role_title', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('current_employer', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('years_exp', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('biography', models.TextField(blank=True, default=None, max_length=1000, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
