# Generated by Django 4.1.4 on 2022-12-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
        ('sectors', '0001_initial'),
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='sectors',
            field=models.ManyToManyField(related_name='apps', to='sectors.sector'),
        ),
        migrations.AddField(
            model_name='app',
            name='tools',
            field=models.ManyToManyField(related_name='apps', to='tools.tool'),
        ),
    ]
