# Generated by Django 4.1.4 on 2022-12-13 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apps', '0001_initial'),
        ('tools', '0001_initial'),
        ('sectors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='app',
            name='sectors',
            field=models.ManyToManyField(related_name='apps', to='sectors.sector'),
        ),
        migrations.AddField(
            model_name='app',
            name='tools',
            field=models.ManyToManyField(related_name='apps', to='tools.tool'),
        ),
    ]
